name: pipeline
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, edited]
    branches: [master]

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - run: yarn

  quality-check:
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - run: yarn

      - run: yarn eslint

      - run: yarn stylelint

      - run: yarn test

  tests:
    needs: quality-check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: get repository code
        uses: actions/checkout@v3

      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - run: yarn

      - run: yarn build:prod

      - run: yarn storybook:build

      - run: yarn test-ui-ci
